# ZSH config
ZSH=$HOME/.oh-my-zsh

: ${HOSTFILE=~/.ssh/known_hosts}

# Android paths
PATH=$PATH:~/Code/android/adt/sdk/platform-tools/
PATH=$PATH:~/Code/android/adt/sdk/tools/

# Binary paths
PATH=$PATH:~/scripts/
PATH=$PATH:~/Code/Go/gopath/bin/

# Various additional paths
export ANDROID_HOME=~/Code/android/adt/sdk/
export GOPATH=~/Code/Go/gopath
export GOROOT=~/Downloads/go/
export SPOTON_HOME=~/Code/spoton2/

# Go cross-compile stuff
export GOOS=linux 
export GOARCH=amd64 
export CGO_ENABLED=0

# Emacs as CLI not GUI
alias emacs="emacs -nw"
alias e="emacs"

# Etc Aliases
alias gospoton="cd $SPOTON_HOME/Components/SpotOn"
alias gofab="cd $SPOTON_HOME/Deployment/Fabric; export PYTHONPATH=./libraries"
alias cola="upd; cola"
alias p="python -i ~/Code/Python/startup.py"
alias ticket="python ~/ticket.py"
alias gogo="cd ~/Code/Go/gopath/src/"
alias open="nautilus --no-desktop"

# Apps
alias uberwriter="/opt/extras.ubuntu.com/uberwriter/bin/uberwriter"

# RC stuff
alias erc="emacs ~/.zshrc"
alias rrc="source ~/.zshrc"
alias ei3="emacs ~/.i3/config"

# SSH
alias s.fireplace="ssh spoton@fireplace.local"
alias s.box="ssh root@box.hydr0.com"
alias s.yolo="ssh spoton@mcyolomac.local"

# Tar
alias tar.in="tar -zcvf"
alias tar.out="tar -zxvf"

# Venv Wrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Code/Python/
source /usr/local/bin/virtualenvwrapper.sh

# Screenshot
alias shot="scrot -s -d 3"

ZSH_THEME="agnoster"

plugins=(git)
export HISTSIZE=""
source $ZSH/oh-my-zsh.sh

# Include some private ass shit
source ~/.includes

# Include ssh ip's
source ~/.remotes
