# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Because everyone else was doing it
export EDITOR="vi"

# Handle editing/reloading this file (super meta bro)
alias erc="$EDITOR ~/.zshrc; rrc"
alias rrc="source ~/.zshrc"

# Because no one will fucking remeber this (insert witty xkcd reference here)
alias tar.in="tar -zcvf"
alias tar.out="tar -zxvf"

# Because Python packages
WORKON_HOME=~/.envs
source /usr/local/bin/virtualenvwrapper.sh

# Fuck it use defaults
ZSH_THEME="eastwood"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# OMZSH Plugins
plugins=(git)

# This is important (I think?)
source $ZSH/oh-my-zsh.sh

# Also this
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin"

# Some SWEEET git shit
g.up () {
    git pull origin $(git rev-parse --abbrev-ref HEAD)
}

g.tfo () {
    git push origin $(git rev-parse --abbrev-ref HEAD)
}

source ~/.remotes
